stages:
  - build
  - test
  - publish

variables:
  typ:
    value: build
    description: "Typ pipeline. Poprawne wersje to 'build', 'test' i 'release'."
  wersja:
    value: 1.0.0
    description: "Numer obecnej wersji"


build-plugins:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - if: $CI_MERGE_REQUEST_IID
    - if: $typ == 'build'
    - if: $typ == 'test'
  tags:
    - W11
  script:
    - 'curl -o "CI Builder.exe" -H @{"PRIVATE-TOKEN"= "$API_KEY"} "https://git.mistaken.pl/api/v4/projects/Barwa%2FCI-Tools/jobs/artifacts/main/raw/build/CI%20Builder.exe?job=build-code-job"'
    - './"CI Builder.exe" $CI_COMMIT_REF_NAME $CI_COMMIT_SHA $CI_CONCURRENT_ID true'
  artifacts:
    paths:
      - plugins.tar.gz 

test-plugins:
  needs: [build-plugins]
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $typ == 'test'
  stage: test
  tags:
   - Linux
  script:
    - 'echo aaaa'
  
build-plugins-publish:
  stage: build
  rules:
    - if: $typ == 'release'
  tags:
    - W11
  script:
    - 'curl -o "CI Builder.exe" -H @{"PRIVATE-TOKEN"= "$API_KEY"} "https://git.mistaken.pl/api/v4/projects/Barwa%2FCI-Tools/jobs/artifacts/main/raw/build/CI%20Builder.exe?job=build-code-job"'
    - './"CI Builder.exe" $CI_COMMIT_REF_NAME $CI_COMMIT_SHA $CI_CONCURRENT_ID true $wersja $CI_COMMIT_REF_NAME'
  artifacts:
    paths:
      - plugins.tar.gz 

test-plugins-publish:
  needs: [build-plugins-publish]
  rules:
    - if: $typ == 'release'
  stage: test
  tags:
   - Linux
  script:
    - 'echo aaaa'
  
publish-plugins:
  needs: [build-plugins-publish, test-plugins-publish]
  rules:
    - if: $typ == 'release'
  stage: publish
  tags:
    - W11
  dependencies:
    - build-plugins-publish
  script:
    - remove-item alias:curl
    - echo $profile
    - notepad $profile
    - echo $wersja > version
    - ls
    - 'curl -InFile "plugins.tar.gz" -Method "Put" -H @{"PRIVATE-TOKEN"= "$API_KEY"} "https://git.mistaken.pl/api/v4/projects/scp-sl%2FMistaken-plugins/packages/generic/plugins/$wersja/plugins.tar.gz"'
    - $env:asset = "{`"name`":`"Plugins`",`"url`":`"https://git.mistaken.pl/api/v4/projects/scp-sl%2FMistaken-plugins/packages/generic/plugins/$wersja/plugins.tar.gz`"}"
    - $env:assetjson = $env:asset | ConvertTo-Json
    - release-cli create --name $CI_COMMIT_TAG --description "Release $CI_COMMIT_TAG" --ref $CI_COMMIT_TAG --tag-name $CI_COMMIT_TAG --assets-link=$env:assetjson
    - $env:sign = <git config --global commit.gpgsign>
    - git config --global commit.gpgsign false
    - git add version
    - git commit -m "bump version"
    - git push
    - git config --global commit.gpgsign $env:sign


