stages:
  - prebuild
  - build

download-builder:
  stage: prebuild
  tags:
    - Windows
  script:
    - curl -L --header "PRIVATE-TOKEN:%CI_JOB_TOKEN%" "https://git.mistaken.pl/Barwa/CI-Tools/-/jobs/artifacts/main/raw/build/CI%20Builder.exe?job=build-code-job"

build-code-job:
  needs: [download-builder]
  stage: build
  tags:
    - Windows
  script:
    - '"CI Builder.exe" %CI_COMMIT_REF_NAME% %CI_COMMIT_SHA% %CI_COMMIT_REF_NAME% true'
  artifacts:
    paths:
      - plugins.tar.gz 
