stages:
  - build

build-plugins:
  stage: build
  tags:
    - W11
  script:
    - 'curl -o "CI Builder.exe" -H @{"PRIVATE-TOKEN"= "a1YCfdhji5bgscqCxFmr"} "https://git.mistaken.pl/api/v4/projects/Barwa%2FCI-Tools/jobs/artifacts/main/raw/build/CI%20Builder.exe?job=build-code-job"'
    - './"CI Builder.exe" $CI_COMMIT_REF_NAME $CI_COMMIT_SHA $CI_CONCURRENT_ID true'
  artifacts:
    paths:
      - plugins.tar.gz 
