//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Mistaken")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Mistaken, All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.0.0")]
[assembly: System.Reflection.AssemblyVersion("3.0.0.0")]


