# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
     - '**'
     - '!master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- name: Remove old artifacts
      #  uses: c-hive/gha-remove-artifacts@v1
      #  with:
      #    age: '1 day'
      - name: Download builder
        # You may pin to the exact commit or the version.
        # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # GitHub token
          github_token: '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'
          # Repository name with owner
          repo: 'Mistaken-Studio/CI-Tools'
          # Artifact name (download all artifacts in not specified)
          name: 'Builder.exe'
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
        uses: NuGet/setup-nuget@v1.0.5
      # Runs a single command using the runners shell
      - name: Build and create tar
        run: |
          echo %GITHUB_WORKSPACE%
          echo %path%
          nuget restore
          echo ---------
          echo %GITHUB_REF%
          echo ---------
          echo %GITHUB_HEAD_REF%
          echo ---------
          echo %GITHUB_BASE_REF%
          echo ---------
          echo %GITHUB_SHA%
          echo ---------
          "%GITHUB_WORKSPACE%/CI Builder.exe" %GITHUB_REF% %GITHUB_SHA% %GITHUB_RUN_NUMBER% true
        shell: cmd
      - name: Hello world action step
        uses: Mistaken-Studio/delete-artifacts-action@1.0
        with:
          leaveNewest: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: plugins.tar.gz
          # A file, directory or wildcard pattern that describes what to upload
          path: plugins.tar.gz
