# This is a basic workflow to help you get started with Actions

name: PR

on: 
  pull_request:
   types: [opened, synchronize, unlocked, ready_for_review]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download builder
        # You may pin to the exact commit or the version.
        # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # GitHub token
          github_token: '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'
          # Repository name with owner
          repo: 'Mistaken-Studio/CI-Tools'
          # Artifact name (download all artifacts in not specified)
          name: 'Builder.exe'
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
        uses: NuGet/setup-nuget@v1.0.5
      # Runs a single command using the runners shell
      - name: Build plugins
        run: |
          echo %GITHUB_WORKSPACE%
          echo %path%
          nuget restore
          echo ---------
          echo %GITHUB_REF%
          echo ---------
          echo ${{ github.event.inputs.version }}
          echo ---------
          echo %INPUT_VERSION%
          echo ---------
          echo %INPUTS_VERSION%
          echo ---------
          echo %GITHUB_SHA%
          echo ---------
          "%GITHUB_WORKSPACE%/CI Builder.exe" %GITHUB_REF% %GITHUB_SHA% %GITHUB_RUN_NUMBER% true
        shell: cmd
      - name: Remove artifacts
        uses: Mistaken-Studio/delete-artifacts-action@1.1.2
        with:
          leaveNewest: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: plugins.tar.gz
          # A file, directory or wildcard pattern that describes what to upload
          path: plugins.tar.gz
  test:
   needs: build
   runs-on: [self-hosted,test]
   steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        # Artifact name
        name: plugins.tar.gz
        # Destination path
        path: /home/barwa/
    - name: Download Tester
        # You may pin to the exact commit or the version.
        # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
      uses: aochmann/actions-download-artifact@1.0.4
      with:
          # GitHub token
          github_token: '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'
          # Repository name with owner
          repo: 'Mistaken-Studio/CI-Tools'
          # Artifact name (download all artifacts in not specified)
          name: 'Tester'
          path: /home/scpsl/server_files
    - name: Unzip files
      run: /home/barwa/unzip.sh
