# This is a basic workflow to help you get started with Actions

name: Release with params

on: 
 workflow_dispatch:
  inputs:
   version:
    description: 'Podaj wersję pluginów do release'     
    required: true
   name:
    description: 'Podaj nazwę wersji'     
    required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
        uses: NuGet/setup-nuget@v1.0.5
      # Runs a single command using the runners shell
      - name: Build plugins
        run: |
          echo %GITHUB_WORKSPACE%
          echo %path%
          nuget restore
          echo ---------
          echo %GITHUB_REF%
          echo ---------
          echo ${{ github.event.inputs.version }}
          echo ---------
          echo %INPUT_VERSION%
          echo ---------
          echo %INPUTS_VERSION%
          echo ---------
          echo %GITHUB_SHA%
          echo ---------
          %GITHUB_WORKSPACE%/CI-Builder.exe %GITHUB_REF% %GITHUB_SHA% %GITHUB_RUN_NUMBER% false ${{ github.event.inputs.version }} ${{ github.event.inputs.name }}
        shell: cmd
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: plugins.tar.gz
          # A file, directory or wildcard pattern that describes what to upload
          path: plugins.tar.gz
  test:
   needs: build
   runs-on: [self-hosted,test]
   steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        # Artifact name
        name: plugins.tar.gz
        # Destination path
        path: /home/barwa/
    - name: Unzip files
      run: /home/barwa/unzip.sh
  publish:
   needs: [build,test]
   runs-on: [self-hosted, Windows]
   steps:
    - uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        path: $GITHUB_WORKSPACE
    - name: Create release
      run: |
        %GITHUB_WORKSPACE%/CI-Publisher.exe ${{ github.event.inputs.version }} %GITHUB_SHA% ${{ github.event.inputs.name }}
      shell: cmd
    - name: Bump version
      uses: EndBug/add-and-commit@v7.2.0
      with:
         add: version
         message: Bump version
